FROM python:3.6.1

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ADD ./requirements.txt /usr/src/app/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ADD . /usr/src/app
ENV FLASK_ENVIRONMENT=prd
CMD celery -A apis.tasks.tasks worker -l info; celery -A apis.tasks.tasks beat -l info
